#!/bin/sh -e

cd `dirname $0`
build_cache=../../build-fprime-automatic-native-ut
fprime-util build --ut "$@"
cp $build_cache/bin/`uname`/Svc_DpWriter_ut_exe .
for file in `find $build_cache -name '*.gcda'`
do
  rm $file
done
./Svc_DpWriter_ut_exe
