// ======================================================================
// \title  BasicStateMachineAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for Basic state machine
// ======================================================================

#include "FppTest/state_machine/internal/initial/BasicStateMachineAc.hpp"
#include "Fw/Types/Assert.hpp"

namespace FppTest {

// ----------------------------------------------------------------------
// Constructors and destructors
// ----------------------------------------------------------------------

BasicStateMachineBase::BasicStateMachineBase() {}

BasicStateMachineBase::~BasicStateMachineBase() {}

// ----------------------------------------------------------------------
// Initialization
// ----------------------------------------------------------------------

void BasicStateMachineBase::init(const FwEnumStoreType id) {
    this->m_id = id;
    this->action_a();
    this->stateEntry_S();
}

// ----------------------------------------------------------------------
// State and junction entry
// ----------------------------------------------------------------------

void BasicStateMachineBase::stateEntry_S() {
    this->action_a();
    this->m_state = State::S;
}

}  // namespace FppTest
