// ======================================================================
// \title  BasicStateMachineAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for Basic state machine
// ======================================================================

#ifndef FppTest_BasicStateMachineAc_HPP
#define FppTest_BasicStateMachineAc_HPP

#include "FpConfig.hpp"

namespace FppTest {

//! A basic state machine
class BasicStateMachineBase {
  PROTECTED:
    // ----------------------------------------------------------------------
    // Types
    // ----------------------------------------------------------------------

    //! The state type
    enum class State : FwEnumStoreType {
        //! State S
        S
    };

  PROTECTED:
    // ----------------------------------------------------------------------
    // Constructors and destructors
    // ----------------------------------------------------------------------

    //! Constructor
    BasicStateMachineBase();

    //! Destructor
    virtual ~BasicStateMachineBase();

  PROTECTED:
    // ----------------------------------------------------------------------
    // Initialization
    // ----------------------------------------------------------------------

    //! Initialize the state machine
    void init(const FwEnumStoreType id  //!< The state machine ID
    );

  PROTECTED:
    // ----------------------------------------------------------------------
    // Actions 
    // ----------------------------------------------------------------------

    //! Action a
    virtual void action_a() = 0;

  PRIVATE:
    // ----------------------------------------------------------------------
    // State and junction entry 
    // ----------------------------------------------------------------------

    //! Enter state S
    void stateEntry_S();

  PROTECTED:
    // ----------------------------------------------------------------------
    // Member variables
    // ----------------------------------------------------------------------

    //! The state machine ID
    FwEnumStoreType m_id = 0;

    //! The state
    State m_state = State::S;
};

};  // namespace FppTest
#endif
