// ======================================================================
// \title  JunctionStateMachineAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for Junction state machine
// ======================================================================

#ifndef FppTest_JunctionStateMachineAc_HPP
#define FppTest_JunctionStateMachineAc_HPP

#include "FpConfig.hpp"

namespace FppTest {

//! A state machine with an initial junction
class JunctionStateMachineBase {
  PROTECTED:
    // ----------------------------------------------------------------------
    // Types
    // ----------------------------------------------------------------------

    //! The state type
    enum class State : FwEnumStoreType {
        //! State S
        S,
        //! State T
        T
    };

  PROTECTED:
    // ----------------------------------------------------------------------
    // Constructors and destructors
    // ----------------------------------------------------------------------

    //! Constructor
    JunctionStateMachineBase();

    //! Destructor
    virtual ~JunctionStateMachineBase();

  public:
    // ----------------------------------------------------------------------
    // Initialization
    // ----------------------------------------------------------------------

    //! Initialize the state machine
    void init(const FwEnumStoreType id  //!< The state machine ID
    );

  PROTECTED:
    // ----------------------------------------------------------------------
    // Actions 
    // ----------------------------------------------------------------------

    //! Action a
    virtual void action_a() = 0;

  PROTECTED:
    // ----------------------------------------------------------------------
    // Guards 
    // ----------------------------------------------------------------------

    //! Guard g
    virtual bool guard_g() = 0;

  PRIVATE:
    // ----------------------------------------------------------------------
    // State and junction entry 
    // ----------------------------------------------------------------------

    //! Enter junction J
    void enter_J();

    //! Enter state S
    void enter_S();

    //! Enter state T
    void enter_T();

  PROTECTED:
    // ----------------------------------------------------------------------
    // Member variables
    // ----------------------------------------------------------------------

    //! The state machine ID
    FwEnumStoreType m_id = 0;

    //! The state
    State m_state = State::S;
};

};  // namespace FppTest
#endif
