// ======================================================================
// \title  JunctionStateMachineAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for Junction state machine
// ======================================================================

#include "FppTest/state_machine/internal/initial/JunctionStateMachineAc.hpp"
#include "Fw/Types/Assert.hpp"

namespace FppTest {

// ----------------------------------------------------------------------
// Constructors and destructors
// ----------------------------------------------------------------------

JunctionStateMachineBase::JunctionStateMachineBase() {}

JunctionStateMachineBase::~JunctionStateMachineBase() {}

// ----------------------------------------------------------------------
// Initialization
// ----------------------------------------------------------------------

void JunctionStateMachineBase::init(const FwEnumStoreType id) {
    this->m_id = id;
    this->action_a();
    this->enter_J();
}

// ----------------------------------------------------------------------
// State and junction entry
// ----------------------------------------------------------------------

void JunctionStateMachineBase::enter_J() {
    if (this->guard_g()) {
        this->action_a();
        this->enter_S();
    } else {
        this->action_a();
        this->action_a();
        this->enter_T();
    }
}

void JunctionStateMachineBase::enter_S() {
    this->action_a();
    this->m_state = State::S;
}

void JunctionStateMachineBase::enter_T() {
    this->action_a();
    this->action_a();
    this->m_state = State::T;
}

}  // namespace FppTest
