// ======================================================================
// \title  NestedStateMachineAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for Nested state machine
// ======================================================================

#ifndef FppTest_NestedStateMachineAc_HPP
#define FppTest_NestedStateMachineAc_HPP

#include "FpConfig.hpp"

namespace FppTest {

//! A basic state machine
class NestedStateMachineBase {
  PROTECTED:
    // ----------------------------------------------------------------------
    // Types
    // ----------------------------------------------------------------------

    //! The state type
    enum class State : FwEnumStoreType {
        //! Uninitialized state
        __FPRIME_AC_UNINITIALIZED,
        //! State S.T
        S_T
    };

  PROTECTED:
    // ----------------------------------------------------------------------
    // Constructors and destructors
    // ----------------------------------------------------------------------

    //! Constructor
    NestedStateMachineBase();

    //! Destructor
    virtual ~NestedStateMachineBase();

  public:
    // ----------------------------------------------------------------------
    // Initialization
    // ----------------------------------------------------------------------

    //! Initialize the state machine
    void init(const FwEnumStoreType id  //!< The state machine ID
    );

  PROTECTED:
    // ----------------------------------------------------------------------
    // Actions 
    // ----------------------------------------------------------------------

    //! Action a
    virtual void action_a() = 0;

  PRIVATE:
    // ----------------------------------------------------------------------
    // State and junction entry 
    // ----------------------------------------------------------------------

    //! Enter state S
    void enter_S();

    //! Enter state S_T
    void enter_S_T();

  PROTECTED:
    // ----------------------------------------------------------------------
    // Member variables
    // ----------------------------------------------------------------------

    //! The state machine ID
    FwEnumStoreType m_id = 0;

    //! The state
    State m_state = State::__FPRIME_AC_UNINITIALIZED;
};

};  // namespace FppTest
#endif
