// ======================================================================
// \title  NestedStateMachineAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for Nested state machine
// ======================================================================

#include "FppTest/state_machine/internal/initial/NestedStateMachineAc.hpp"
#include "Fw/Types/Assert.hpp"

namespace FppTest {

// ----------------------------------------------------------------------
// Constructors and destructors
// ----------------------------------------------------------------------

NestedStateMachineBase::NestedStateMachineBase() {}

NestedStateMachineBase::~NestedStateMachineBase() {}

// ----------------------------------------------------------------------
// Initialization
// ----------------------------------------------------------------------

void NestedStateMachineBase::init(const FwEnumStoreType id) {
    this->m_id = id;
    this->action_a();
    this->enter_S();
}

// ----------------------------------------------------------------------
// State and junction entry
// ----------------------------------------------------------------------

void NestedStateMachineBase::enter_S() {
    this->action_a();
    this->action_a();
    this->enter_S_T();
}

void NestedStateMachineBase::enter_S_T() {
    this->action_a();
    this->action_a();
    this->action_a();
    this->m_state = State::S_T;
}

}  // namespace FppTest
