#!/bin/sh -e

dir=`dirname $0`
cd $dir

./build --ut "$@"
cp ../../build-fprime-automatic-native-ut/bin/`uname`/Svc_DpManager_ut_exe .
for file in `find ../.. -name '*.gcda'`
do
  rm $file
done
./Svc_DpManager_ut_exe
