// ======================================================================
// \title  DpTestDpComponentAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for Data product base class for DpTest component
// ======================================================================

#include "Fw/Types/Assert.hpp"
#include "FppTest/dp/DpTestDpComponentAc.hpp"

namespace FppTest {

  // ----------------------------------------------------------------------
  // Construction and destruction
  // ----------------------------------------------------------------------

  DpTestDpComponentBase ::
    DpTestDpComponentBase(const char* compName) :
      DpTestComponentBase(compName)
  {

  }

  DpTestDpComponentBase ::
    ~DpTestDpComponentBase()
  {

  }

}
